folders:
  - path: "/Users/torrance/Code/permsEnforce/src/github.com/torrance/permsEnforce/testFolder"
    user: "torrance"
    dir_perms: "0755"
    file_perms: "0664"

  - path: "/Users/torrance/Code/permsEnforce/src/github.com/torrance/permsEnforce/testFolder/folder2"
    group: "everyone"

  - path: "/Users/torrance/Code/permsEnforce/src/github.com/torrance/permsEnforce/testFolder/folder1"
    dir_perms: "775"
    file_perms: "664"
    group: "staff"
